server:
    port: 18043
    address: localhost
    ssl:
        protocol: TLS
        key-store: classpath:lowcode.keystore
        #key-store-password: lowcode@159283Jaf&
        key-store-password: ENC(gVMptBep6lVzcPkedEd1YckcmOrwbG34kQkP8oIPkcxTQhsLi1EKhMhLNa/24v6Mod2py1GIP83K85PGiC61Sg==)
        key-store-type: JKS
    servlet: 
        context-path: /lowcode
        session: 
            timeout: 7200
              
spring: 
    application: 
        name: lowcode-project
      
    datasource:
        lcdp-engine:
            username: linux
            password: ENC(DjL9IplOMrYzKIpvOTNTpCAjZzOm7CAaftYOeT7sPD6wiaumT0Aqx8/PKJckYYb5)
            jdbcUrl: jdbc:mysql://[fd15:4ba5:5a2b:1009::10]:3306/zpaas_lowcode_revise?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
            driver-class-name: com.mysql.cj.jdbc.Driver
        camunda:
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbcUrl: jdbc:mysql://[fd15:4ba5:5a2b:1009::10]:3306/camunda?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
            username: linux
            password: ENC(DjL9IplOMrYzKIpvOTNTpCAjZzOm7CAaftYOeT7sPD6wiaumT0Aqx8/PKJckYYb5)
        
    elasticsearch:
        rest:
            uris: http://192.168.203.128:9200
            
    servlet:
        multipart:
            enabled: true
            max-file-size: 3MB
            max-request-size: 20MB

#jasypt加密,将密钥作为环境变量参数在执行应用的启动命令时传入
jasypt:
    encryptor:
        password: lowcode@ajfiwUU&
        algorithm: PBEWITHHMACSHA512ANDAES_256

caffeine:
    name: caffeineCache
    spec: maximumSize=10000

camunda:
    bpm:
        admin-user:
            id: demo
            #password: demo
            password: ENC(uS+HkhZqPf4QWydXF7eQYcbPvmz7FV+HgkfQTlmN5UNbaBMb11Mt3DNwQjwP2QSR)
            firstName: Demo
        generic-properties:
            properties:
                historyTimeToLive: P365D
    filter:
        create: All tasks

       
logging:
    #config: classpath:logback.xml
    level:
        root : info
        cn.zpaas.lowcode : DEBUG
        #cn.zpaas.lowcode.be.engine.ability: TRACE
        #cn.zpaas.lowcode.be.engine.flow.node: TRACE
        #cn.zpaas.lowcode.be.engine.controller : INFO
        #cn.zpaas.lowcode.be.engine.proxy : INFO
        org.springframework.jdbc: ERROR
        org.apache.kafka.clients: WARN
    pattern:
        console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(%-40.40logger{39}){cyan}[%line] %clr(:){faint} %.-1024m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
        #file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(%-40.40logger{39}){cyan}[%line] %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    #path: "./logs/"
    #file: "./logs/lcdp.log"
    #file.max-size: 10MB

snowFlake:
    dataCenterId: 2
    machineId: 2

### 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
xxl:
    job:
        admin:
            addresses: http://192.168.10.10:8099/xxl-job-admin
### 执行器通讯TOKEN [选填]：非空时启用；
        accessToken: default_token
### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
        executor:
            appname: xxl-job-executor-lowcode
### 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
            address:
### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
            ip:
### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
            port: 9999
### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
            logpath: /Users/zjy/vs_workspace/zpaas-lowcode/zpaas-lowcode-starter/logs
### 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
            logretentiondays: 30

init:
    param:
        systemId: 
        tenantId: 
        servicePath: service
        streamServicePath: streamService
        batchServicePath: batchService
        fileUploadServicePath: fileUploadService
        fileDownloadServicePath: fileDownloadService
        tempFilePath: ./tempFile/
        loginInfoKey: loginInfo
        stream:
            timeout: 60000

service:
    registry:
        registryTime: 60000
        registryTimeout: 120000

        