
import { createApp } from 'vue'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
import {Wallet, DataBoard, Postcard, DocumentCopy, Guide, Notification, Service, Folder, TrendCharts, List, Timer, Star, Edit, ArrowLeft, ArrowRight, ArrowDown, Message, Lock, Location, DataAnalysis, Document,Setting, Menu,CoffeeCup, Fold, Management, Expand, RefreshRight, CircleCheckFilled,Grid, Close, Check, Histogram, Download, Plus, Coin, MessageBox, Tools, OfficeBuilding, ChatDotRound, Connection, Delete, Search, Collection, ZoomIn, LocationFilled} from '@element-plus/icons-vue'
import App from '../components/workbench.vue'
import router from '@/router/workbench'

const app = createApp(App)
app.use(ElementPlus)
app.use(router)
app.component('Wallet', Wallet)
app.component('DataBoard', DataBoard)
app.component('Postcard', Postcard)
app.component('DocumentCopy', DocumentCopy)
app.component('Guide', Guide)
app.component('Service', Service)
app.component('Notification', Notification)
app.component('Folder', Folder)
app.component('Timer', Timer)
app.component('Star', Star)
app.component('Edit', Edit)
app.component('ArrowLeft', ArrowLeft)
app.component('ArrowDown', ArrowDown)
app.component('ArrowRight', ArrowRight)
app.component('DataAnalysis', DataAnalysis)
app.component('CoffeeCup', CoffeeCup)
app.component('Fold', Fold)
app.component('message', Message)
app.component('setting', Setting)
app.component('grid', Grid)
app.component('plus', Plus)
app.component('histogram', Histogram)
app.component('location', Location)
app.component('document', Document)
app.component('coin', Coin)
app.component('MessageBox', MessageBox)
app.component('Tools', Tools)
app.component('OfficeBuilding', OfficeBuilding)
app.component('ChatDotRound', ChatDotRound)
app.component('Connection', Connection)
app.component('Download', Download)
app.component('Delete', Delete)
app.component('search', Search)
app.component('Collection', Collection)
app.component('ZoomIn', ZoomIn)
app.component('Check', Check)
app.component('Close', Close)
app.component('Expand', Expand)
app.component('Management', Management)
app.component('CircleCheckFilled', CircleCheckFilled)
app.component('Menu', Menu)
app.component('Lock', Lock)
app.component('RefreshRight', RefreshRight)
app.component('LocationFilled', LocationFilled)
app.component('List', List)
app.component('TrendCharts', TrendCharts)
app.mount('#app')


